### ISSUE TITLE
Can this library be used to upload TeamCity plugins

### ISSUE THREAD

**Issue by rodm** [JetBrains/plugin-repository-rest-client#12]
I've developed the [gradle-teamcity-plugin](https://github.com/rodm/gradle-teamcity-plugin) and would like to add support to publish/upload plugins similar to the publish task of the [gradle-intellij-plugin](https://github.com/JetBrains/gradle-intellij-plugin)

I tried using the command line interface with the host set to https://plugins.jetbrains.com/teamcity, the plugin id set to an id of an existing plugin and setting username and password. The command logged it was about to upload the plugin but returned rather quickly with no upload occurring and no error message.

Any thoughts on whether this library can be used to publish TeamCity plugins? If not are there any plans to add support?

**Comment by mikhailvink** [comment]
It's not possible right now because at this point TeamCity plugins can't be hosted at https://plugins.jetbrains.com as binaries, the download link to TeamCity plugin always points to some external URL.

We are planning to add support for TeamCity plugins binaries hosting on https://plugins.jetbrains.com very soon. I'm not sure about the exact ETA because we need to introduce some changes to the plugins descriptor, but we're targeting to bring it live sometime in March 2017.

**Comment by satamas** [comment]
We've supported TeamCity binaries on plugins.jetbrains.com side. Issue can be closed.
